export class Field{
    static account = 'account'
    static accountBankName = 'accountBankName'
    static accountBankNumber = 'accountBankNumber'
    static oppositeAccount = 'oppositeAccount'
    static oppositeName = 'oppositeName'
    static oppositeBankNumber = 'oppositeBankNumber'
    static oppositeBankName = 'oppositeBankName'
    static money = 'money'
    static leftMoney = 'leftMoney'
    static inOrOut = 'inOrOut'
    static tradeType = 'tradeType'
    static tradeTime = 'tradeTime'
    static tradeNumber = 'tradeNumber'
    static tradeDesc = 'tradeDesc'
    static tradeResult = 'tradeResult'
    static caseID = 'caseID'
    static isThird = 'isThird'
    static payeeName = 'payeeName'
    static payeeNumber = 'payeeNumber'
    static lowerAccount = 'lowerAccount'
}